# Generated by Django 5.1.3 on 2024-12-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio_anterior', models.CharField(max_length=11, verbose_name='Precio anterior')),
                ('precio_nuevo', models.CharField(max_length=11, verbose_name='Precio nuevo')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Imagen')),
            ],
        ),
    ]
