# Generated by Django 5.1.3 on 2024-12-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio anterior')),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio nuevo')),
            ],
        ),
    ]
