# Generated by Django 5.1.3 on 2024-12-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_productos_precio_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_original',
            field=models.CharField(blank=True, max_length=15, verbose_name='Precio original'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_anterior',
            field=models.CharField(blank=True, max_length=15, verbose_name='Precio anterior'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_nuevo',
            field=models.CharField(blank=True, max_length=15, verbose_name='Precio nuevo'),
        ),
    ]
