# Generated by Django 5.1.3 on 2024-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_productos_precio_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='tiene_descuento',
            field=models.BooleanField(default=False, verbose_name='Tiene descuento?'),
        ),
    ]
