# Generated by Django 5.1.3 on 2024-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_productos_imagen2_productos_imagen3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, verbose_name='Descripción'),
        ),
    ]
