# Generated by Django 5.1.3 on 2024-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=110, verbose_name='Descripción'),
        ),
    ]
