# Generated by Django 5.1.3 on 2024-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_productos_talle1_productos_talle2_productos_talle3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255, verbose_name='Producto')),
                ('talle', models.CharField(max_length=50, verbose_name='Talle')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.CharField(max_length=15, verbose_name='Precio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
            ],
        ),
    ]
