# Generated by Django 5.1.3 on 2024-12-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compra',
            name='medio_de_pago',
            field=models.CharField(blank=True, max_length=25, verbose_name='Medio de pago'),
        ),
    ]
