# Generated by Django 5.1.3 on 2024-12-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_compras_delete_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
            ],
        ),
        migrations.AlterField(
            model_name='compras',
            name='envio',
            field=models.CharField(choices=[('Envío', 'Envío'), ('Retiro', 'Retiro')], max_length=30),
        ),
        migrations.AddField(
            model_name='compras',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='web.cliente'),
        ),
    ]
